// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zceeepifmqpblfudfczg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZWVlcGlmbXFwYmxmdWRmY3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODA1MzEsImV4cCI6MjA3Mjk1NjUzMX0.G1NN5xgrkRZ8TFp2cRkuPLyB_RZWP5mEKx4T9TQbhhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);